name: Sync Dashboard to Profile

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dashboard repo
        uses: actions/checkout@v3

      - name: Copy dashboard files
        run: |
          mkdir sync
          cp Readme.md sync/README_dashboard.md
          cp -r charts sync/

      - name: Push to LONGDKZdev repo (profile)
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository: LONGDKZdev/LONGDKZdev
          branch: main
          directory: sync
          commit_message: "Sync from Dashboard repo"
